/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import project.service.DebtService;
import project.service.ManagementService;
// import service.DebtService;
// import service.ManagementService;

/**
 *
 * @author USER
 */
public class Dashboard extends javax.swing.JFrame {

        /**
         * Creates new form Dashboard2
         */
        private ManagementService mService = new ManagementService();
        private DebtService dService = new DebtService();

        public Dashboard() {
                this.setExtendedState(Dashboard.MAXIMIZED_BOTH);
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jToggleButton4 = new javax.swing.JToggleButton();
                jToggleButton7 = new javax.swing.JToggleButton();
                jToggleButton8 = new javax.swing.JToggleButton();
                jToggleButton9 = new javax.swing.JToggleButton();
                jPanel4 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jProgressBar1 = new javax.swing.JProgressBar();
                jProgressBar2 = new javax.swing.JProgressBar();
                jLabel7 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jProgressBar3 = new javax.swing.JProgressBar();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jProgressBar4 = new javax.swing.JProgressBar();
                jLabel15 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(
                                new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                jLabel1.setBackground(new java.awt.Color(108, 99, 255));
                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(108, 99, 255));
                jLabel1.setText("TreasuryM");

                jLabel2.setBackground(new java.awt.Color(196, 196, 196));
                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(196, 196, 196));
                jLabel2.setText("Main menu");

                jToggleButton4.setBackground(new java.awt.Color(108, 99, 255));
                jToggleButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jToggleButton4.setForeground(new java.awt.Color(108, 99, 255));
                jToggleButton4.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/asset/icon/dashboard_black_24dp.png"))); // NOI18N
                jToggleButton4.setText("Dashboard");
                jToggleButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jToggleButton4.setBorderPainted(false);
                jToggleButton4.setContentAreaFilled(false);
                jToggleButton4.setFocusPainted(false);
                jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jToggleButton4ActionPerformed(evt);
                        }
                });

                jToggleButton7.setBackground(new java.awt.Color(197, 197, 197));
                jToggleButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jToggleButton7.setForeground(new java.awt.Color(197, 197, 197));
                jToggleButton7.setText("Debt menu");
                jToggleButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jToggleButton7.setBorderPainted(false);
                jToggleButton7.setContentAreaFilled(false);
                jToggleButton7.setFocusPainted(false);
                jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jToggleButton7ActionPerformed(evt);
                        }
                });

                jToggleButton8.setBackground(new java.awt.Color(197, 197, 197));
                jToggleButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jToggleButton8.setForeground(new java.awt.Color(197, 197, 197));
                jToggleButton8.setText("Management");
                jToggleButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jToggleButton8.setBorderPainted(false);
                jToggleButton8.setContentAreaFilled(false);
                jToggleButton8.setFocusPainted(false);
                jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jToggleButton8ActionPerformed(evt);
                        }
                });

                jToggleButton9.setBackground(new java.awt.Color(197, 197, 197));
                jToggleButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jToggleButton9.setForeground(new java.awt.Color(197, 197, 197));
                jToggleButton9.setText("Person menu");
                jToggleButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jToggleButton9.setBorderPainted(false);
                jToggleButton9.setContentAreaFilled(false);
                jToggleButton9.setFocusPainted(false);
                jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jToggleButton9ActionPerformed(evt);
                        }
                });

                jPanel4.setBackground(new java.awt.Color(108, 99, 255));
                jPanel4.setForeground(new java.awt.Color(108, 99, 255));

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                                                5, Short.MAX_VALUE));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                                                27, Short.MAX_VALUE));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(16, 16, 16)
                                                                .addComponent(jLabel2))
                                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(78, 78, 78)
                                                                .addComponent(jLabel1))
                                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(35, 35, 35)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jToggleButton8)
                                                                                .addComponent(jToggleButton9)
                                                                                .addComponent(jToggleButton7)))
                                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(25, 25, 25)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jToggleButton4)))
                                                .addContainerGap(66, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(14, 14, 14).addComponent(jLabel1)
                                                .addGap(31, 31, 31).addComponent(jLabel2).addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jToggleButton4).addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(10, 10, 10).addComponent(jToggleButton8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jToggleButton9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jToggleButton7).addGap(263, 263, 263)));

                jPanel3.setBackground(new java.awt.Color(108, 99, 255));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                                                0, Short.MAX_VALUE));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                                                56, Short.MAX_VALUE));

                jLabel4.setBackground(new java.awt.Color(108, 99, 255));
                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(108, 99, 255));
                jLabel4.setText("Welcome back!");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel5.setText("Don't forget for collect the treasury");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel8.setText("Treasury");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel6.setText("Total yang sudah lunas");

                jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel9.setText("Total yang belum lunas");

                jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel11.setText("Debt");

                jProgressBar1.setForeground(new java.awt.Color(108, 99, 255));
                jProgressBar1.setValue(mService.percentLunas);

                jProgressBar2.setForeground(new java.awt.Color(108, 99, 255));
                jProgressBar2.setValue(mService.percentBelomLunas);

                jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel7.setText(mService.percentLunas.toString() + "%");

                jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel10.setText(mService.percentBelomLunas.toString() + "%");

                jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel12.setText("Total yang sudah lunas");

                jProgressBar3.setForeground(new java.awt.Color(108, 99, 255));
                jProgressBar3.setValue(dService.percentLunas);

                jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel13.setText(dService.percentLunas.toString() + "%");

                jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel14.setText("Total yang belum lunas");

                jProgressBar4.setForeground(new java.awt.Color(108, 99, 255));
                jProgressBar4.setValue(dService.percentBelomLunas);

                jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel15.setText(dService.percentBelomLunas.toString() + "%");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel5).addComponent(jLabel4)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel6)
                                                                                .addGap(28, 28, 28)
                                                                                .addComponent(jProgressBar1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel7))
                                                                .addComponent(jLabel8)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel9)
                                                                                .addGap(28, 28, 28)
                                                                                .addComponent(jProgressBar2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel10))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel12)
                                                                                .addGap(28, 28, 28)
                                                                                .addComponent(jProgressBar3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel13))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel14)
                                                                                .addGap(28, 28, 28)
                                                                                .addComponent(jProgressBar4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel15))
                                                                .addComponent(jLabel11))
                                                .addContainerGap(155, Short.MAX_VALUE))
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18).addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5).addGap(44, 44, 44).addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jLabel6,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jProgressBar1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                20,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jLabel9,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jProgressBar2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                20,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(jLabel10))
                                                .addGap(43, 43, 43).addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jLabel12,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jProgressBar3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                20,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(jLabel13))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jLabel14,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jProgressBar4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                20,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(jLabel15))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));

                getContentPane().add(jPanel1);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton4ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jToggleButton4ActionPerformed

        private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton7ActionPerformed
                new Debt().setVisible(true);
                this.setVisible(false);
        }// GEN-LAST:event_jToggleButton7ActionPerformed

        private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton8ActionPerformed
                new Management().setVisible(true);
                this.setVisible(false);
        }// GEN-LAST:event_jToggleButton8ActionPerformed

        private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton9ActionPerformed
                new Person().setVisible(true);
                this.setVisible(false);
        }// GEN-LAST:event_jToggleButton9ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Dashboard().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JProgressBar jProgressBar1;
        private javax.swing.JProgressBar jProgressBar2;
        private javax.swing.JProgressBar jProgressBar3;
        private javax.swing.JProgressBar jProgressBar4;
        private javax.swing.JToggleButton jToggleButton4;
        private javax.swing.JToggleButton jToggleButton7;
        private javax.swing.JToggleButton jToggleButton8;
        private javax.swing.JToggleButton jToggleButton9;
        // End of variables declaration//GEN-END:variables
}
